import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[100vh] flex flex-col`}>
        {" "}
        <Navbar />
        <div className="flex grow">
          <div className="min-w-[250px] border-r-2 border-gray-300">
            <Sidebar />
          </div>

          <div className="flex flex-col grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
